services:
  MetaModels\AttributeTranslatedContentArticleBundle\Attribute\AttributeTypeFactory:
    arguments:
      - '@database_connection'
      - '@metamodels.table_manipulator'
    tags:
      - { name: metamodels.attribute_factory }

  MetaModels\AttributeTranslatedContentArticleBundle\EventListener\BackendEventListener:
    public: true
    arguments:
      - '@database_connection'

  MetaModels\AttributeTranslatedContentArticleBundle\Controller\Backend\MetaModelController:
    tags: ['controller.service_arguments']

#  MetaModels\AttributeTranslatedContentArticleBundle\FileUsage\FileUsageProvider:
#    public: true
#    arguments:
#      $factory: '@metamodels.factory'
#      $urlGenerator: '@router'
#      $requestStack: '@request_stack'
#      $csrfTokenManager: '@contao.csrf.token_manager'
#      $connection: '@database_connection'
#      $csrfTokenName: '%contao.csrf_token_name%'
#      $uploadPath: '%contao.upload_path%'
#    tags:
#      - { name: contao_file_usage.provider }
