services:
  MetaModels\AttributeTranslatedContentArticleBundle\Attribute\AttributeTypeFactory:
    arguments:
      - '@database_connection'
      - '@metamodels.table_manipulator'
    tags:
      - { name: metamodels.attribute_factory }

  MetaModels\AttributeTranslatedContentArticleBundle\EventListener\BackendEventListener:
    public: true
    arguments:
      - '@database_connection'

  MetaModels\AttributeTranslatedContentArticleBundle\Controller\Backend\MetaModelController:
    tags: ['controller.service_arguments']
